global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['api:8000']  
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 
    scheme: 'http'
